#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTHUEXE1")]
	public partial class dbQLThuexeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void InsertTIENDOTHUEXE(TIENDOTHUEXE instance);
    partial void UpdateTIENDOTHUEXE(TIENDOTHUEXE instance);
    partial void DeleteTIENDOTHUEXE(TIENDOTHUEXE instance);
    partial void InsertBLOGDULICH(BLOGDULICH instance);
    partial void UpdateBLOGDULICH(BLOGDULICH instance);
    partial void DeleteBLOGDULICH(BLOGDULICH instance);
    partial void InsertCTHD(CTHD instance);
    partial void UpdateCTHD(CTHD instance);
    partial void DeleteCTHD(CTHD instance);
    partial void InsertCUAHANG(CUAHANG instance);
    partial void UpdateCUAHANG(CUAHANG instance);
    partial void DeleteCUAHANG(CUAHANG instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHUVUC(KHUVUC instance);
    partial void UpdateKHUVUC(KHUVUC instance);
    partial void DeleteKHUVUC(KHUVUC instance);
    partial void InsertLOAISANPHAM(LOAISANPHAM instance);
    partial void UpdateLOAISANPHAM(LOAISANPHAM instance);
    partial void DeleteLOAISANPHAM(LOAISANPHAM instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertSANPHAM(SANPHAM instance);
    partial void UpdateSANPHAM(SANPHAM instance);
    partial void DeleteSANPHAM(SANPHAM instance);
    #endregion
		
		public dbQLThuexeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLTHUEXEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLThuexeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLThuexeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLThuexeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLThuexeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<TIENDOTHUEXE> TIENDOTHUEXEs
		{
			get
			{
				return this.GetTable<TIENDOTHUEXE>();
			}
		}
		
		public System.Data.Linq.Table<BLOGDULICH> BLOGDULICHes
		{
			get
			{
				return this.GetTable<BLOGDULICH>();
			}
		}
		
		public System.Data.Linq.Table<CTHD> CTHDs
		{
			get
			{
				return this.GetTable<CTHD>();
			}
		}
		
		public System.Data.Linq.Table<CUAHANG> CUAHANGs
		{
			get
			{
				return this.GetTable<CUAHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHUVUC> KHUVUCs
		{
			get
			{
				return this.GetTable<KHUVUC>();
			}
		}
		
		public System.Data.Linq.Table<LOAISANPHAM> LOAISANPHAMs
		{
			get
			{
				return this.GetTable<LOAISANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<SANPHAM> SANPHAMs
		{
			get
			{
				return this.GetTable<SANPHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAdmin;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private string _hoten;
		
		private string _sodienthoai;
		
		private string _diachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAdminChanging(int value);
    partial void OnIDAdminChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAdmin
		{
			get
			{
				return this._IDAdmin;
			}
			set
			{
				if ((this._IDAdmin != value))
				{
					this.OnIDAdminChanging(value);
					this.SendPropertyChanging();
					this._IDAdmin = value;
					this.SendPropertyChanged("IDAdmin");
					this.OnIDAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIENDOTHUEXE")]
	public partial class TIENDOTHUEXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTD;
		
		private string _tinhtrangthuexe;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTDChanging(int value);
    partial void OnmaTDChanged();
    partial void OntinhtrangthuexeChanging(string value);
    partial void OntinhtrangthuexeChanged();
    #endregion
		
		public TIENDOTHUEXE()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTD
		{
			get
			{
				return this._maTD;
			}
			set
			{
				if ((this._maTD != value))
				{
					this.OnmaTDChanging(value);
					this.SendPropertyChanging();
					this._maTD = value;
					this.SendPropertyChanged("maTD");
					this.OnmaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrangthuexe", DbType="NVarChar(20)")]
		public string tinhtrangthuexe
		{
			get
			{
				return this._tinhtrangthuexe;
			}
			set
			{
				if ((this._tinhtrangthuexe != value))
				{
					this.OntinhtrangthuexeChanging(value);
					this.SendPropertyChanging();
					this._tinhtrangthuexe = value;
					this.SendPropertyChanged("tinhtrangthuexe");
					this.OntinhtrangthuexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIENDOTHUEXE_HOADON", Storage="_HOADONs", ThisKey="maTD", OtherKey="tinhtrangthue")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TIENDOTHUEXE = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TIENDOTHUEXE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BLOGDULICH")]
	public partial class BLOGDULICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTD;
		
		private string _tieude;
		
		private string _hinhanh;
		
		private string _mota;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _maND;
		
		private System.Nullable<int> _luotxem;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTDChanging(int value);
    partial void OnmaTDChanged();
    partial void OntieudeChanging(string value);
    partial void OntieudeChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydangChanged();
    partial void OnmaNDChanging(System.Nullable<int> value);
    partial void OnmaNDChanged();
    partial void OnluotxemChanging(System.Nullable<int> value);
    partial void OnluotxemChanged();
    #endregion
		
		public BLOGDULICH()
		{
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTD
		{
			get
			{
				return this._maTD;
			}
			set
			{
				if ((this._maTD != value))
				{
					this.OnmaTDChanging(value);
					this.SendPropertyChanging();
					this._maTD = value;
					this.SendPropertyChanged("maTD");
					this.OnmaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(300)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this.OntieudeChanging(value);
					this.SendPropertyChanging();
					this._tieude = value;
					this.SendPropertyChanged("tieude");
					this.OntieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(100)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(2000)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", DbType="Int")]
		public System.Nullable<int> maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luotxem", DbType="Int")]
		public System.Nullable<int> luotxem
		{
			get
			{
				return this._luotxem;
			}
			set
			{
				if ((this._luotxem != value))
				{
					this.OnluotxemChanging(value);
					this.SendPropertyChanging();
					this._luotxem = value;
					this.SendPropertyChanged("luotxem");
					this.OnluotxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_BLOGDULICH", Storage="_NGUOIDUNG", ThisKey="maND", OtherKey="maND", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.BLOGDULICHes.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.BLOGDULICHes.Add(this);
						this._maND = value.maND;
					}
					else
					{
						this._maND = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHD")]
	public partial class CTHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHD;
		
		private System.Nullable<int> _maCH;
		
		private int _maSP;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<decimal> _thanhtien;
		
		private System.Nullable<int> _isSell;
		
		private EntityRef<CUAHANG> _CUAHANG;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(int value);
    partial void OnmaHDChanged();
    partial void OnmaCHChanging(System.Nullable<int> value);
    partial void OnmaCHChanged();
    partial void OnmaSPChanging(int value);
    partial void OnmaSPChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnthanhtienChanging(System.Nullable<decimal> value);
    partial void OnthanhtienChanged();
    partial void OnisSellChanging(System.Nullable<int> value);
    partial void OnisSellChanged();
    #endregion
		
		public CTHD()
		{
			this._CUAHANG = default(EntityRef<CUAHANG>);
			this._HOADON = default(EntityRef<HOADON>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCH", DbType="Int")]
		public System.Nullable<int> maCH
		{
			get
			{
				return this._maCH;
			}
			set
			{
				if ((this._maCH != value))
				{
					if (this._CUAHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCHChanging(value);
					this.SendPropertyChanging();
					this._maCH = value;
					this.SendPropertyChanged("maCH");
					this.OnmaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSell", DbType="Int")]
		public System.Nullable<int> isSell
		{
			get
			{
				return this._isSell;
			}
			set
			{
				if ((this._isSell != value))
				{
					this.OnisSellChanging(value);
					this.SendPropertyChanging();
					this._isSell = value;
					this.SendPropertyChanged("isSell");
					this.OnisSellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUAHANG_CTHD", Storage="_CUAHANG", ThisKey="maCH", OtherKey="maCH", IsForeignKey=true)]
		public CUAHANG CUAHANG
		{
			get
			{
				return this._CUAHANG.Entity;
			}
			set
			{
				CUAHANG previousValue = this._CUAHANG.Entity;
				if (((previousValue != value) 
							|| (this._CUAHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CUAHANG.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._CUAHANG.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._maCH = value.maCH;
					}
					else
					{
						this._maCH = default(Nullable<int>);
					}
					this.SendPropertyChanged("CUAHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_HOADON", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(int);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTHD", Storage="_SANPHAM", ThisKey="maSP", OtherKey="maSP", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._maSP = value.maSP;
					}
					else
					{
						this._maSP = default(int);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUAHANG")]
	public partial class CUAHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCH;
		
		private string _tentaikhoan;
		
		private string _matkhau;
		
		private string _tenCH;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private string _email;
		
		private EntitySet<CTHD> _CTHDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCHChanging(int value);
    partial void OnmaCHChanged();
    partial void OntentaikhoanChanging(string value);
    partial void OntentaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OntenCHChanging(string value);
    partial void OntenCHChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public CUAHANG()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCH
		{
			get
			{
				return this._maCH;
			}
			set
			{
				if ((this._maCH != value))
				{
					this.OnmaCHChanging(value);
					this.SendPropertyChanging();
					this._maCH = value;
					this.SendPropertyChanged("maCH");
					this.OnmaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentaikhoan", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string tentaikhoan
		{
			get
			{
				return this._tentaikhoan;
			}
			set
			{
				if ((this._tentaikhoan != value))
				{
					this.OntentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._tentaikhoan = value;
					this.SendPropertyChanged("tentaikhoan");
					this.OntentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenCH
		{
			get
			{
				return this._tenCH;
			}
			set
			{
				if ((this._tenCH != value))
				{
					this.OntenCHChanging(value);
					this.SendPropertyChanging();
					this._tenCH = value;
					this.SendPropertyChanged("tenCH");
					this.OntenCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUAHANG_CTHD", Storage="_CTHDs", ThisKey="maCH", OtherKey="maCH")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.CUAHANG = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.CUAHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHD;
		
		private System.Nullable<System.DateTime> _ngaythue;
		
		private System.Nullable<System.DateTime> _ngaytra;
		
		private System.Nullable<int> _maND;
		
		private System.Nullable<int> _tinhtrangthue;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntityRef<TIENDOTHUEXE> _TIENDOTHUEXE;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(int value);
    partial void OnmaHDChanged();
    partial void OnngaythueChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythueChanged();
    partial void OnngaytraChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytraChanged();
    partial void OnmaNDChanging(System.Nullable<int> value);
    partial void OnmaNDChanged();
    partial void OntinhtrangthueChanging(System.Nullable<int> value);
    partial void OntinhtrangthueChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._TIENDOTHUEXE = default(EntityRef<TIENDOTHUEXE>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythue", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythue
		{
			get
			{
				return this._ngaythue;
			}
			set
			{
				if ((this._ngaythue != value))
				{
					this.OnngaythueChanging(value);
					this.SendPropertyChanging();
					this._ngaythue = value;
					this.SendPropertyChanged("ngaythue");
					this.OnngaythueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytra", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytra
		{
			get
			{
				return this._ngaytra;
			}
			set
			{
				if ((this._ngaytra != value))
				{
					this.OnngaytraChanging(value);
					this.SendPropertyChanging();
					this._ngaytra = value;
					this.SendPropertyChanged("ngaytra");
					this.OnngaytraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", DbType="Int")]
		public System.Nullable<int> maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrangthue", DbType="Int")]
		public System.Nullable<int> tinhtrangthue
		{
			get
			{
				return this._tinhtrangthue;
			}
			set
			{
				if ((this._tinhtrangthue != value))
				{
					if (this._TIENDOTHUEXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntinhtrangthueChanging(value);
					this.SendPropertyChanging();
					this._tinhtrangthue = value;
					this.SendPropertyChanged("tinhtrangthue");
					this.OntinhtrangthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_CTHDs", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIENDOTHUEXE_HOADON", Storage="_TIENDOTHUEXE", ThisKey="tinhtrangthue", OtherKey="maTD", IsForeignKey=true)]
		public TIENDOTHUEXE TIENDOTHUEXE
		{
			get
			{
				return this._TIENDOTHUEXE.Entity;
			}
			set
			{
				TIENDOTHUEXE previousValue = this._TIENDOTHUEXE.Entity;
				if (((previousValue != value) 
							|| (this._TIENDOTHUEXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIENDOTHUEXE.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._TIENDOTHUEXE.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._tinhtrangthue = value.maTD;
					}
					else
					{
						this._tinhtrangthue = default(Nullable<int>);
					}
					this.SendPropertyChanged("TIENDOTHUEXE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_HOADON", Storage="_NGUOIDUNG", ThisKey="maND", OtherKey="maND", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._maND = value.maND;
					}
					else
					{
						this._maND = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUVUC")]
	public partial class KHUVUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _makv;
		
		private string _tenkv;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakvChanging(int value);
    partial void OnmakvChanged();
    partial void OntenkvChanging(string value);
    partial void OntenkvChanged();
    #endregion
		
		public KHUVUC()
		{
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int makv
		{
			get
			{
				return this._makv;
			}
			set
			{
				if ((this._makv != value))
				{
					this.OnmakvChanging(value);
					this.SendPropertyChanging();
					this._makv = value;
					this.SendPropertyChanged("makv");
					this.OnmakvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenkv
		{
			get
			{
				return this._tenkv;
			}
			set
			{
				if ((this._tenkv != value))
				{
					this.OntenkvChanging(value);
					this.SendPropertyChanging();
					this._tenkv = value;
					this.SendPropertyChanged("tenkv");
					this.OntenkvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_SANPHAM", Storage="_SANPHAMs", ThisKey="makv", OtherKey="makv")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAISANPHAM")]
	public partial class LOAISANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maloaiSP;
		
		private string _tenloaiSP;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiSPChanging(int value);
    partial void OnmaloaiSPChanged();
    partial void OntenloaiSPChanging(string value);
    partial void OntenloaiSPChanged();
    #endregion
		
		public LOAISANPHAM()
		{
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maloaiSP
		{
			get
			{
				return this._maloaiSP;
			}
			set
			{
				if ((this._maloaiSP != value))
				{
					this.OnmaloaiSPChanging(value);
					this.SendPropertyChanging();
					this._maloaiSP = value;
					this.SendPropertyChanged("maloaiSP");
					this.OnmaloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloaiSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenloaiSP
		{
			get
			{
				return this._tenloaiSP;
			}
			set
			{
				if ((this._tenloaiSP != value))
				{
					this.OntenloaiSPChanging(value);
					this.SendPropertyChanging();
					this._tenloaiSP = value;
					this.SendPropertyChanged("tenloaiSP");
					this.OntenloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANPHAM_SANPHAM", Storage="_SANPHAMs", ThisKey="maloaiSP", OtherKey="maloaiSP")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANPHAM = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maND;
		
		private string _tentaikhoan;
		
		private string _matkhau;
		
		private string _hoten;
		
		private string _sodienthoai;
		
		private string _email;
		
		private EntitySet<BLOGDULICH> _BLOGDULICHes;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNDChanging(int value);
    partial void OnmaNDChanged();
    partial void OntentaikhoanChanging(string value);
    partial void OntentaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._BLOGDULICHes = new EntitySet<BLOGDULICH>(new Action<BLOGDULICH>(this.attach_BLOGDULICHes), new Action<BLOGDULICH>(this.detach_BLOGDULICHes));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentaikhoan", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string tentaikhoan
		{
			get
			{
				return this._tentaikhoan;
			}
			set
			{
				if ((this._tentaikhoan != value))
				{
					this.OntentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._tentaikhoan = value;
					this.SendPropertyChanged("tentaikhoan");
					this.OntentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(15)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(25)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_BLOGDULICH", Storage="_BLOGDULICHes", ThisKey="maND", OtherKey="maND")]
		public EntitySet<BLOGDULICH> BLOGDULICHes
		{
			get
			{
				return this._BLOGDULICHes;
			}
			set
			{
				this._BLOGDULICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_HOADON", Storage="_HOADONs", ThisKey="maND", OtherKey="maND")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_SANPHAM", Storage="_SANPHAMs", ThisKey="maND", OtherKey="maND")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BLOGDULICHes(BLOGDULICH entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_BLOGDULICHes(BLOGDULICH entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
	public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSP;
		
		private string _tenSP;
		
		private System.Nullable<int> _maloaiSP;
		
		private int _giathue;
		
		private string _mota;
		
		private string _image;
		
		private string _khungxe;
		
		private string _mausac;
		
		private string _phankhoi;
		
		private string _hangxe;
		
		private string _bienso;
		
		private string _diachi;
		
		private System.Nullable<int> _makv;
		
		private System.Nullable<int> _maND;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntityRef<KHUVUC> _KHUVUC;
		
		private EntityRef<LOAISANPHAM> _LOAISANPHAM;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSPChanging(int value);
    partial void OnmaSPChanged();
    partial void OntenSPChanging(string value);
    partial void OntenSPChanged();
    partial void OnmaloaiSPChanging(System.Nullable<int> value);
    partial void OnmaloaiSPChanged();
    partial void OngiathueChanging(int value);
    partial void OngiathueChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnkhungxeChanging(string value);
    partial void OnkhungxeChanged();
    partial void OnmausacChanging(string value);
    partial void OnmausacChanged();
    partial void OnphankhoiChanging(string value);
    partial void OnphankhoiChanged();
    partial void OnhangxeChanging(string value);
    partial void OnhangxeChanged();
    partial void OnbiensoChanging(string value);
    partial void OnbiensoChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnmakvChanging(System.Nullable<int> value);
    partial void OnmakvChanged();
    partial void OnmaNDChanging(System.Nullable<int> value);
    partial void OnmaNDChanged();
    #endregion
		
		public SANPHAM()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._KHUVUC = default(EntityRef<KHUVUC>);
			this._LOAISANPHAM = default(EntityRef<LOAISANPHAM>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maSP
		{
			get
			{
				return this._maSP;
			}
			set
			{
				if ((this._maSP != value))
				{
					this.OnmaSPChanging(value);
					this.SendPropertyChanging();
					this._maSP = value;
					this.SendPropertyChanged("maSP");
					this.OnmaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenSP
		{
			get
			{
				return this._tenSP;
			}
			set
			{
				if ((this._tenSP != value))
				{
					this.OntenSPChanging(value);
					this.SendPropertyChanging();
					this._tenSP = value;
					this.SendPropertyChanged("tenSP");
					this.OntenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiSP", DbType="Int")]
		public System.Nullable<int> maloaiSP
		{
			get
			{
				return this._maloaiSP;
			}
			set
			{
				if ((this._maloaiSP != value))
				{
					if (this._LOAISANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiSPChanging(value);
					this.SendPropertyChanging();
					this._maloaiSP = value;
					this.SendPropertyChanged("maloaiSP");
					this.OnmaloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giathue", DbType="Int NOT NULL")]
		public int giathue
		{
			get
			{
				return this._giathue;
			}
			set
			{
				if ((this._giathue != value))
				{
					this.OngiathueChanging(value);
					this.SendPropertyChanging();
					this._giathue = value;
					this.SendPropertyChanged("giathue");
					this.OngiathueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khungxe", DbType="NVarChar(25)")]
		public string khungxe
		{
			get
			{
				return this._khungxe;
			}
			set
			{
				if ((this._khungxe != value))
				{
					this.OnkhungxeChanging(value);
					this.SendPropertyChanging();
					this._khungxe = value;
					this.SendPropertyChanged("khungxe");
					this.OnkhungxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mausac", DbType="NVarChar(25)")]
		public string mausac
		{
			get
			{
				return this._mausac;
			}
			set
			{
				if ((this._mausac != value))
				{
					this.OnmausacChanging(value);
					this.SendPropertyChanging();
					this._mausac = value;
					this.SendPropertyChanged("mausac");
					this.OnmausacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phankhoi", DbType="VarChar(10)")]
		public string phankhoi
		{
			get
			{
				return this._phankhoi;
			}
			set
			{
				if ((this._phankhoi != value))
				{
					this.OnphankhoiChanging(value);
					this.SendPropertyChanging();
					this._phankhoi = value;
					this.SendPropertyChanged("phankhoi");
					this.OnphankhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hangxe", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string hangxe
		{
			get
			{
				return this._hangxe;
			}
			set
			{
				if ((this._hangxe != value))
				{
					this.OnhangxeChanging(value);
					this.SendPropertyChanging();
					this._hangxe = value;
					this.SendPropertyChanged("hangxe");
					this.OnhangxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bienso", DbType="VarChar(10)")]
		public string bienso
		{
			get
			{
				return this._bienso;
			}
			set
			{
				if ((this._bienso != value))
				{
					this.OnbiensoChanging(value);
					this.SendPropertyChanging();
					this._bienso = value;
					this.SendPropertyChanged("bienso");
					this.OnbiensoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makv", DbType="Int")]
		public System.Nullable<int> makv
		{
			get
			{
				return this._makv;
			}
			set
			{
				if ((this._makv != value))
				{
					if (this._KHUVUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakvChanging(value);
					this.SendPropertyChanging();
					this._makv = value;
					this.SendPropertyChanged("makv");
					this.OnmakvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", DbType="Int")]
		public System.Nullable<int> maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTHD", Storage="_CTHDs", ThisKey="maSP", OtherKey="maSP")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_SANPHAM", Storage="_KHUVUC", ThisKey="makv", OtherKey="makv", IsForeignKey=true)]
		public KHUVUC KHUVUC
		{
			get
			{
				return this._KHUVUC.Entity;
			}
			set
			{
				KHUVUC previousValue = this._KHUVUC.Entity;
				if (((previousValue != value) 
							|| (this._KHUVUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHUVUC.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._KHUVUC.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._makv = value.makv;
					}
					else
					{
						this._makv = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHUVUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANPHAM_SANPHAM", Storage="_LOAISANPHAM", ThisKey="maloaiSP", OtherKey="maloaiSP", IsForeignKey=true)]
		public LOAISANPHAM LOAISANPHAM
		{
			get
			{
				return this._LOAISANPHAM.Entity;
			}
			set
			{
				LOAISANPHAM previousValue = this._LOAISANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAISANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAISANPHAM.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._LOAISANPHAM.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._maloaiSP = value.maloaiSP;
					}
					else
					{
						this._maloaiSP = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAISANPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_SANPHAM", Storage="_NGUOIDUNG", ThisKey="maND", OtherKey="maND", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._maND = value.maND;
					}
					else
					{
						this._maND = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
	}
}
#pragma warning restore 1591
